const Langs = {
  en_US: {
    save: 'Save',
    copyMarkdown: 'Copy Markdown',
    copyHtml: 'Copy HTML',
    toggleOutline: 'Toggle outline',
    editingMode: 'Editing mode',
    wysiwygMode: 'Visual editing',
    splitViewMode: 'Split source view',
    outdentList: 'Outdent list item (Shift+Tab)',
    indentList: 'Indent list item (Tab)',
    mathBlock: 'Insert formula block',
    mathInline: 'Insert inline formula',
    detailsBlock: 'Insert collapsible section',
    detailsSummary: 'Section title',
    detailsContent: 'Section content',
    editDetailsTitle: 'Edit section title',
    alertNote: 'Note alert',
    alertTip: 'Tip alert',
    alertImportant: 'Important alert',
    alertWarning: 'Warning alert',
    alertCaution: 'Caution alert',
    alertContent: 'Alert content',
    alertToggle: 'GitHub Alert',
    changeAlertType: 'Change Alert type',
    quoteToggle: 'Quote / GitHub Alert (toggle)',
    quotePlain: 'Plain quote',
    quoteContent: 'Quote content',
    deleteTable: 'Delete table',
    deleteQuote: 'Delete quote',
    deleteAlert: 'Delete GitHub Alert',
    deleteDetails: 'Delete collapsible section',
    deleteCodeBlock: 'Delete code block',
    deleteMathBlock: 'Delete formula block',
    reloadWorkspaceStyle: 'Reload workspace CSS',
    normalizeFormatting: 'Normalize document formatting',
    normalizeFormattingConfirm: 'Rewrite this document using Vditor/Lute formatting? This intentionally changes Markdown source formatting.',
    resetConfig: 'Reset config',
    resetConfirm: "Are you sure you want to reset Markdown Interactor's configuration?",
  },
  ja_JP: {
    save: '保存する',
    toggleOutline: 'アウトラインの表示を切り替え',
    editingMode: '編集モード',
    wysiwygMode: 'ビジュアル編集',
    splitViewMode: 'ソース分割表示',
    outdentList: 'リストのインデントを減らす (Shift+Tab)',
    indentList: 'リストをインデント (Tab)',
    mathBlock: '数式ブロックを挿入',
    mathInline: 'インライン数式を挿入',
    detailsBlock: '折りたたみセクションを挿入',
    detailsSummary: 'セクションのタイトル',
    detailsContent: 'セクションの内容',
    editDetailsTitle: 'セクションのタイトルを編集',
    alertNote: 'Note アラート',
    alertTip: 'Tip アラート',
    alertImportant: 'Important アラート',
    alertWarning: 'Warning アラート',
    alertCaution: 'Caution アラート',
    alertContent: 'アラートの内容',
    alertToggle: 'GitHub Alert',
    changeAlertType: 'Alert の種類を変更',
    quoteToggle: '引用 / GitHub Alert（切り替え）',
    quotePlain: '通常の引用',
    quoteContent: '引用の内容',
    deleteQuote: '引用を削除',
    deleteAlert: 'GitHub Alert を削除',
    deleteDetails: '折りたたみセクションを削除',
    deleteCodeBlock: 'コードブロックを削除',
    deleteMathBlock: '数式ブロックを削除',
    normalizeFormatting: '文書の書式を正規化',
    normalizeFormattingConfirm: 'Vditor/Lute の書式でこの文書を書き換えますか？Markdown ソースの書式が変更されます。',
  },
  ko_KR: {
    save: '저장',
    toggleOutline: '개요 표시 전환',
    editingMode: '편집 모드',
    wysiwygMode: '비주얼 편집',
    splitViewMode: '소스 분할 보기',
    outdentList: '목록 내어쓰기 (Shift+Tab)',
    indentList: '목록 들여쓰기 (Tab)',
    mathBlock: '수식 블록 삽입',
    mathInline: '인라인 수식 삽입',
    detailsBlock: '접을 수 있는 섹션 삽입',
    detailsSummary: '섹션 제목',
    detailsContent: '섹션 내용',
    editDetailsTitle: '섹션 제목 편집',
    alertNote: 'Note 알림',
    alertTip: 'Tip 알림',
    alertImportant: 'Important 알림',
    alertWarning: 'Warning 알림',
    alertCaution: 'Caution 알림',
    alertContent: '알림 내용',
    alertToggle: 'GitHub Alert',
    changeAlertType: 'Alert 유형 변경',
    quoteToggle: '인용 / GitHub Alert (전환)',
    quotePlain: '일반 인용',
    quoteContent: '인용 내용',
    deleteQuote: '인용 삭제',
    deleteAlert: 'GitHub Alert 삭제',
    deleteDetails: '접이식 섹션 삭제',
    deleteCodeBlock: '코드 블록 삭제',
    deleteMathBlock: '수식 블록 삭제',
    normalizeFormatting: '문서 서식 정규화',
    normalizeFormattingConfirm: 'Vditor/Lute 서식으로 이 문서를 다시 작성할까요? Markdown 원본 서식이 변경됩니다.',
  },
  zh_CN: {
    save: '保存',
    copyMarkdown: '复制 Markdown',
    copyHtml: '复制 HTML',
    toggleOutline: '切换目录显示',
    editingMode: '编辑模式',
    wysiwygMode: '可视化编辑',
    splitViewMode: '源码分屏',
    outdentList: '减少列表缩进 (Shift+Tab)',
    indentList: '增加列表缩进 (Tab)',
    mathBlock: '插入公式块',
    mathInline: '插入行内公式',
    detailsBlock: '插入折叠区',
    detailsSummary: '折叠标题',
    detailsContent: '折叠内容',
    editDetailsTitle: '编辑折叠标题',
    alertNote: 'Note 提示',
    alertTip: 'Tip 提示',
    alertImportant: 'Important 重要提示',
    alertWarning: 'Warning 警告',
    alertCaution: 'Caution 注意',
    alertContent: 'Alert 内容',
    alertToggle: 'GitHub Alert',
    changeAlertType: '切换 Alert 类型',
    quoteToggle: '引用 / GitHub Alert（开关）',
    quotePlain: '普通引用',
    quoteContent: '引用内容',
    deleteTable: '删除表格',
    deleteQuote: '删除引用区域',
    deleteAlert: '删除 GitHub Alert',
    deleteDetails: '删除折叠区域',
    deleteCodeBlock: '删除代码块',
    deleteMathBlock: '删除公式块',
    reloadWorkspaceStyle: '刷新加载工作区 CSS',
    normalizeFormatting: '规范化文档格式',
    normalizeFormattingConfirm: '确定使用 Vditor/Lute 的格式重写此文档吗？这会有意改变 Markdown 源码排版。',
    resetConfig: '重置配置',
    resetConfirm: '确定要重置 Markdown Interactor 的配置吗？',
  },
}

export const lang = (() => {
  let l: any = navigator.language.replace('-', '_')
  if (!Langs[l]) {
    l = 'en_US'
  }
  return l
})()

export function t(msg: string) {
  return (Langs[lang] && Langs[lang][msg]) || Langs.en_US[msg]
}
