// Generated by the vditor-i18n plugin in scripts/build-media.mjs from Vditor's
// own locale bundles, keyed by language tag.
declare module 'virtual:vditor-i18n' {
  export const vditorI18n: Record<string, Record<string, string>>;
}
